project_name: gnoic
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/karimra/gnoic/app.version={{.Version}} -X github.com/karimra/gnoic/app.commit={{.ShortCommit}} -X github.com/karimra/gnoic/app.date={{.Date}} -X github.com/karimra/gnoic/app.gitURL={{.GitURL}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - gnoic
    image_templates:
      - "ghcr.io/karimra/gnoic:latest"
      - 'ghcr.io/karimra/gnoic:{{ replace .Version "v" ""}}'
    dockerfile: goreleaser.dockerfile
    skip_push: false
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv7
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: gnoic
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv7
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    vendor: gnoic
    homepage: https://gnoic.kmrd.dev
    maintainer: Karim Radhouani <medkarimrdi@gmail.com>
    description: gNOI CLI client
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
